version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: yiiman-safeline-mgt-1
      APP_PORT: 1443



  postgres:
    container_name: safeline-pg
    restart: always
    image: chaitin/safeline-postgres:15.2
    volumes:
      - ${APP_DATA_DIR}/postgres/resources/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=safeline-ce
      - POSTGRES_PASSWORD=safeline-ce
    command: [postgres, -c, max_connections=600]
    healthcheck:
      test: pg_isready -U safeline-ce -d safeline-ce
  mgt:
    container_name: yiiman-safeline-mgt-1
    restart: always

    image: chaitin/safeline-mgt-g:7.5.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/safeline/resources/mgt:/app/data
      - ${APP_DATA_DIR}/safeline/nginx:/app/log/nginx:z
      - ${APP_DATA_DIR}/safeline/resources/sock:/app/sock
      - /var/run:/app/run
    healthcheck:
      test: curl -k -f https://localhost:1443/api/open/health
    environment:
      - MGT_PG=postgres://safeline-ce:safeline-ce@safeline-pg/safeline-ce?sslmode=disable
    depends_on:
      - postgres
      - fvm
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  detect:
    container_name: safeline-detector
    restart: always
    image: chaitin/safeline/safeline-detector-g:7.5.0
    volumes:
      - ${APP_DATA_DIR}/safeline/resources/detector:/resources/detector
      - ${APP_DATA_DIR}/safeline/logs/detector:/logs/detector
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_DIR=/logs/detector
  tengine:
    container_name: safeline-tengine
    restart: always
    image: chaitin/safeline-tengine-g:7.5.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - ${APP_DATA_DIR}/safeline/resources/nginx:/etc/nginx
      - ${APP_DATA_DIR}/safeline/resources/detector:/resources/detector
      - ${APP_DATA_DIR}/safeline/resources/chaos:/resources/chaos
      - ${APP_DATA_DIR}/safeline/logs/nginx:/var/log/nginx:z
      - ${APP_DATA_DIR}/safeline/resources/cache:/usr/local/nginx/cache
      - ${APP_DATA_DIR}/safeline/resources/sock:/app/sock
    environment:
      - TCD_MGT_API=https://yiiman-safeline-mgt-1:1443/api/open/publish/server
      - TCD_SNSERVER=safeline-detector:8000
      # deprecated
      - SNSERVER_ADDR=safeline-detector:8000
      - CHAOS_ADDR=safeline-chaos
    ulimits:
      nofile: 131072
    network_mode: host
  luigi:
    container_name: safeline-luigi
    restart: always
    image: chaitin/safeline-luigi-g:7.5.0
    environment:
      - MGT_IP=yiiman-safeline-mgt-1
      - LUIGI_PG=postgres://safeline-ce:safeline-ce@safeline-pg/safeline-ce?sslmode=disable
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/safeline/resources/luigi:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - detect
      - mgt
  fvm:
    container_name: safeline-fvm
    restart: always
    image: chaitin/safeline-fvm-g:7.5.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  chaos:
    container_name: safeline-chaos
    restart: always
    image: chaitin/safeline-chaos-g:7.5.0
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      - DB_ADDR=postgres://safeline-ce:safeline-ce@safeline-pg/safeline-ce?sslmode=disable
    volumes:
      - ${APP_DATA_DIR}/safeline/resources/sock:/app/sock
      - ${APP_DATA_DIR}/safeline/resources/chaos:/app/chaos


        
