version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: yiiman-safeline-waf_mgt_1
      APP_PORT: 1443



  postgres:
    container_name: safeline-pg
    restart: always
    image: chaitin/safeline-postgres:15.2
    volumes:
      - ${APP_DATA_DIR}/postgres/resources/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=safeline-ce
      - POSTGRES_PASSWORD=safeline-ce
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.2
    command: [postgres, -c, max_connections=600]
    healthcheck:
      test: pg_isready -U safeline-ce -d safeline-ce
  mgt:
    container_name: yiiman-safeline-mgt
    restart: always
    hostname: safeline-waf_mgt_1
    image: chaitin/safeline-mgt-g-lts:7.5.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/safeline/resources/mgt:/app/data
      - ${APP_DATA_DIR}/safeline/nginx:/app/log/nginx:z
      - ${APP_DATA_DIR}/safeline/resources/sock:/app/sock
      - /var/run:/app/run
    healthcheck:
      test: curl -k -f https://localhost:1443/api/open/health
    environment:
      - MGT_PG=postgres://safeline-ce:safeline-ce@safeline-pg/safeline-ce?sslmode=disable
    depends_on:
      - postgres
      - fvm
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.4
  detect:
    container_name: safeline-detector
    restart: always
    image: chaitin/safeline/safeline-detector-g-lts:7.5.0
    volumes:
      - ${APP_DATA_DIR}/safeline/resources/detector:/resources/detector
      - ${APP_DATA_DIR}/safeline/logs/detector:/logs/detector
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_DIR=/logs/detector
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.5
  tengine:
    container_name: safeline-tengine
    restart: always
    image: chaitin/safeline-tengine-g-lts:7.5.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - ${APP_DATA_DIR}/safeline/resources/nginx:/etc/nginx
      - ${APP_DATA_DIR}/safeline/resources/detector:/resources/detector
      - ${APP_DATA_DIR}/safeline/resources/chaos:/resources/chaos
      - ${APP_DATA_DIR}/safeline/logs/nginx:/var/log/nginx:z
      - ${APP_DATA_DIR}/safeline/resources/cache:/usr/local/nginx/cache
      - ${APP_DATA_DIR}/safeline/resources/sock:/app/sock
    environment:
      - TCD_MGT_API=https://172.22.222.4:1443/api/open/publish/server
      - TCD_SNSERVER=172.22.222.5:8000
      # deprecated
      - SNSERVER_ADDR=172.22.222.5:8000
      - CHAOS_ADDR=172.22.222.10
    ulimits:
      nofile: 131072
    network_mode: host
  luigi:
    container_name: safeline-luigi
    restart: always
    image: chaitin/safeline-luigi-g-lts:7.5.0
    environment:
      - MGT_IP=172.22.222.4
      - LUIGI_PG=postgres://safeline-ce:safeline-ce@safeline-pg/safeline-ce?sslmode=disable
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/safeline/resources/luigi:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - detect
      - mgt
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.7
  fvm:
    container_name: safeline-fvm
    restart: always
    image: chaitin/safeline-fvm-g-lts:7.5.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.8
  chaos:
    container_name: safeline-chaos
    restart: always
    image: chaitin/safeline-chaos-g-lts:7.5.0
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      - DB_ADDR=postgres://safeline-ce:safeline-ce@safeline-pg/safeline-ce?sslmode=disable
    volumes:
      - ${APP_DATA_DIR}/safeline/resources/sock:/app/sock
      - ${APP_DATA_DIR}/safeline/resources/chaos:/app/chaos
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.10

        
networks:
  safeline-ce:
    name: safeline-ce
    driver: bridge
    ipam:
      driver: default
      config:
        - gateway: 172.22.222.1
          subnet: 172.22.222.0/24
    driver_opts:
      com.docker.network.bridge.name: safeline-ce
